//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.956.0 using the following command:
// xscgen --namespace=CzPttXml --nullable --collectionType=System.Array --collectionSettersMode=Public --netCore -o CzPttXml ../jrutil/src/CzPtt/czptt.xsd
namespace CzPttXml
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.956.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TransportIdentifier", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("PlannedTransportIdentifiers", Namespace="")]
    public partial class TransportIdentifier
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("ObjectType")]
        public ObjectType ObjectType { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Pattern: [0-9]{1,4}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{1,4}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Company")]
        public string Company { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Pattern: [0-9A-Z*\-]{12}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9A-Z*\\-]{12}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Core")]
        public string Core { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Pattern: [0-9A-Z]{2}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9A-Z]{2}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Variant")]
        public string Variant { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("TimetableYear")]
        public string TimetableYear { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.956.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ObjectType", Namespace="", AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute("ObjectType", Namespace="")]
    public enum ObjectType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("TR")]
        Tr,
        
        [System.Xml.Serialization.XmlEnumAttribute("PA")]
        Pa,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.956.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PlannedCalendar", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("PlannedCalendar", Namespace="")]
    public partial class PlannedCalendar
    {
        
        /// <summary>
        /// <para xml:lang="en">Pattern: [10]+.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[10]+")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("BitmapDays")]
        public string BitmapDays { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("ValidityPeriod")]
        public ValidityPeriod ValidityPeriod { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.956.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ValidityPeriod", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("ValidityPeriod", Namespace="")]
    public partial class ValidityPeriod
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("StartDateTime", DataType="dateTime")]
        public System.DateTime StartDateTime { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("EndDateTime", DataType="dateTime")]
        public System.DateTime EndDateTimeValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the EndDateTime property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool EndDateTimeValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> EndDateTime
        {
            get
            {
                if (this.EndDateTimeValueSpecified)
                {
                    return this.EndDateTimeValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.EndDateTimeValue = value.GetValueOrDefault();
                this.EndDateTimeValueSpecified = value.HasValue;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.956.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CZPTTCISMessage", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("CZPTTCISMessage", Namespace="")]
    public partial class CzpttcisMessage
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private TransportIdentifier[] _identifiers;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlArrayAttribute("Identifiers")]
        [System.Xml.Serialization.XmlArrayItemAttribute("PlannedTransportIdentifiers")]
        public TransportIdentifier[] Identifiers
        {
            get
            {
                return _identifiers;
            }
            set
            {
                _identifiers = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="CzpttcisMessage" /> class.</para>
        /// </summary>
        public CzpttcisMessage()
        {
            this._identifiers = System.Array.Empty<TransportIdentifier>();
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("CZPTTCreation", DataType="dateTime")]
        public System.DateTime CzpttCreation { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("CZPTTInformation")]
        public CzpttInformation CzpttInformation { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("NetworkSpecificParameter")]
        public NetworkSpecificParameter NetworkSpecificParameter { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.956.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Identifiers", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Identifiers", Namespace="")]
    public partial class Identifiers
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private TransportIdentifier[] _plannedTransportIdentifiers;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("PlannedTransportIdentifiers")]
        public TransportIdentifier[] PlannedTransportIdentifiers
        {
            get
            {
                return _plannedTransportIdentifiers;
            }
            set
            {
                _plannedTransportIdentifiers = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Identifiers" /> class.</para>
        /// </summary>
        public Identifiers()
        {
            this._plannedTransportIdentifiers = System.Array.Empty<TransportIdentifier>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.956.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CZPTTInformation", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("CZPTTInformation", Namespace="")]
    public partial class CzpttInformation
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("PlannedCalendar")]
        public PlannedCalendar PlannedCalendar { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private CzpttLocation[] _czpttLocation;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("CZPTTLocation")]
        public CzpttLocation[] CzpttLocation
        {
            get
            {
                return _czpttLocation;
            }
            set
            {
                _czpttLocation = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="CzpttInformation" /> class.</para>
        /// </summary>
        public CzpttInformation()
        {
            this._czpttLocation = System.Array.Empty<CzpttLocation>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.956.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CZPTTLocation", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("CZPTTLocation", Namespace="")]
    public partial class CzpttLocation
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Location")]
        public Location Location { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("TimingAtLocation")]
        public TimingAtLocation TimingAtLocation { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Pattern: [0-9]{1,4}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{1,4}")]
        [System.Xml.Serialization.XmlElementAttribute("ResponsibleRU")]
        public string ResponsibleRu { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Pattern: [0-9]{1,4}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{1,4}")]
        [System.Xml.Serialization.XmlElementAttribute("ResponsibleIM")]
        public string ResponsibleIm { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("TrainType")]
        public TrainType TrainTypeValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the TrainType property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool TrainTypeValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<TrainType> TrainType
        {
            get
            {
                if (this.TrainTypeValueSpecified)
                {
                    return this.TrainTypeValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.TrainTypeValue = value.GetValueOrDefault();
                this.TrainTypeValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Pattern: [0-9A-Z]{2}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9A-Z]{2}")]
        [System.Xml.Serialization.XmlElementAttribute("TrafficType")]
        public string TrafficType { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Pattern: [0-9A-B]{2,4}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9A-B]{2,4}")]
        [System.Xml.Serialization.XmlElementAttribute("CommercialTrafficType")]
        public string CommercialTrafficType { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Pattern: [0-9]{5,6}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{5,6}")]
        [System.Xml.Serialization.XmlElementAttribute("OperationalTrainNumber")]
        public string OperationalTrainNumber { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private TrainActivity[] _trainActivity;
        
        [System.Xml.Serialization.XmlElementAttribute("TrainActivity")]
        public TrainActivity[] TrainActivity
        {
            get
            {
                return _trainActivity;
            }
            set
            {
                _trainActivity = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the TrainActivity collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TrainActivitySpecified
        {
            get
            {
                return ((this.TrainActivity != null) 
                            && (this.TrainActivity.Length != 0));
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="CzpttLocation" /> class.</para>
        /// </summary>
        public CzpttLocation()
        {
            this._trainActivity = System.Array.Empty<TrainActivity>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.956.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Location", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Location", Namespace="")]
    public partial class Location
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("CountryCodeISO")]
        public string CountryCodeIso { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Pattern: [0-9]{5}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{5}")]
        [System.Xml.Serialization.XmlElementAttribute("LocationPrimaryCode")]
        public string LocationPrimaryCode { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("PrimaryLocationName")]
        public string PrimaryLocationName { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("LocationSubsidiaryIdentification")]
        public LocationSubsidiaryIdentification LocationSubsidiaryIdentification { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.956.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("LocationSubsidiaryIdentification", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("LocationSubsidiaryIdentification", Namespace="")]
    public partial class LocationSubsidiaryIdentification
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("LocationSubsidiaryCode")]
        public LocationSubsidiaryCode LocationSubsidiaryCode { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Pattern: [0-9]{1,4}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{1,4}")]
        [System.Xml.Serialization.XmlElementAttribute("AllocationCompany")]
        public string AllocationCompany { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("LocationSubsidiaryName")]
        public string LocationSubsidiaryName { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.956.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("LocationSubsidiaryCode", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("LocationSubsidiaryCode", Namespace="")]
    public partial class LocationSubsidiaryCode
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("LocationSubsidiaryTypeCode")]
        public string LocationSubsidiaryTypeCode { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.956.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TimingAtLocation", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("TimingAtLocation", Namespace="")]
    public partial class TimingAtLocation
    {
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("DwellTime")]
        public decimal DwellTimeValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the DwellTime property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool DwellTimeValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<decimal> DwellTime
        {
            get
            {
                if (this.DwellTimeValueSpecified)
                {
                    return this.DwellTimeValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.DwellTimeValue = value.GetValueOrDefault();
                this.DwellTimeValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private Timing[] _timing;
        
        [System.Xml.Serialization.XmlElementAttribute("Timing")]
        public Timing[] Timing
        {
            get
            {
                return _timing;
            }
            set
            {
                _timing = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Timing collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TimingSpecified
        {
            get
            {
                return ((this.Timing != null) 
                            && (this.Timing.Length != 0));
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="TimingAtLocation" /> class.</para>
        /// </summary>
        public TimingAtLocation()
        {
            this._timing = System.Array.Empty<Timing>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.956.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Timing", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Timing", Namespace="")]
    public partial class Timing
    {
        
        /// <summary>
        /// <para xml:lang="en">Pattern: \d{2}:\d{2}:\d{2}\.\d+\+\d{2}:\d{2}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("\\d{2}:\\d{2}:\\d{2}\\.\\d+\\+\\d{2}:\\d{2}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Time")]
        public string Time { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Offset")]
        public string Offset { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("TimingQualifierCode")]
        public TimingTimingQualifierCode TimingQualifierCode { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.956.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TimingTimingQualifierCode", Namespace="", AnonymousType=true)]
    public enum TimingTimingQualifierCode
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("ALA")]
        Ala,
        
        [System.Xml.Serialization.XmlEnumAttribute("ALD")]
        Ald,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.956.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TrainType", Namespace="", AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute("TrainType", Namespace="")]
    public enum TrainType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.956.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TrainActivity", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("TrainActivity", Namespace="")]
    public partial class TrainActivity
    {
        
        /// <summary>
        /// <para xml:lang="en">Pattern: [0-9A-Z]{4}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9A-Z]{4}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("TrainActivityType")]
        public string TrainActivityType { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.956.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("NetworkSpecificParameter", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("NetworkSpecificParameter", Namespace="")]
    public partial class NetworkSpecificParameter
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string[] _name;
        
        [System.Xml.Serialization.XmlElementAttribute("Name")]
        public string[] Name
        {
            get
            {
                return _name;
            }
            set
            {
                _name = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Name collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NameSpecified
        {
            get
            {
                return ((this.Name != null) 
                            && (this.Name.Length != 0));
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="NetworkSpecificParameter" /> class.</para>
        /// </summary>
        public NetworkSpecificParameter()
        {
            this._name = System.Array.Empty<string>();
            this._value = System.Array.Empty<string>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string[] _value;
        
        [System.Xml.Serialization.XmlElementAttribute("Value")]
        public string[] Value
        {
            get
            {
                return _value;
            }
            set
            {
                _value = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Value collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValueSpecified
        {
            get
            {
                return ((this.Value != null) 
                            && (this.Value.Length != 0));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.956.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CZCanceledPTTMessage", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("CZCanceledPTTMessage", Namespace="")]
    public partial class CzCanceledPttMessage
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private TransportIdentifier[] _plannedTransportIdentifiers;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("PlannedTransportIdentifiers")]
        public TransportIdentifier[] PlannedTransportIdentifiers
        {
            get
            {
                return _plannedTransportIdentifiers;
            }
            set
            {
                _plannedTransportIdentifiers = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="CzCanceledPttMessage" /> class.</para>
        /// </summary>
        public CzCanceledPttMessage()
        {
            this._plannedTransportIdentifiers = System.Array.Empty<TransportIdentifier>();
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("CZPTTCancelation", DataType="dateTime")]
        public System.DateTime CzpttCancelation { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("PlannedCalendar")]
        public PlannedCalendar PlannedCalendar { get; set; }
    }
}
